version: 2

builds:
  - main: .
    binary: martis
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos: [darwin, linux, windows]
    goarch: [amd64, arm64]

archives:
  - format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: checksums.txt

brews:
  - name: martis
    repository:
      owner: wahyuakbarwibowo
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/wahyuakbarwibowo/martis
    description: Terminal REST client
    license: MIT
    test: system "#{bin}/martis", "version"

scoops:
  - name: martis
    repository:
      owner: wahyuakbarwibowo
      name: scoop-bucket
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/wahyuakbarwibowo/martis
    description: Terminal REST client
    license: MIT
